#!/usr/bin/env python
# -*- coding: utf-8 -*-
# 
# Copyright 2014 Marcus Müller.
# 
# This is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
# 
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this software; see the file COPYING.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street,
# Boston, MA 02110-1301, USA.
#

import argparse
from mtb.remote_agent import remote_agent
from mtb import benchmarking_task as bt

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
#    parser.add_argument("CONTROL_ADDRESS")
    parser.add_argument("-t","--task", type=argparse.FileType('r'))
    parser.add_argument("-o","--output", type=argparse.FileType('w'), default='-')
    
    args = parser.parse_args()
    ra = remote_agent()
    if args.task:
        t = bt.task.load(args.task)
        res = ra.execute_all(t, args.output)
