#!/usr/bin/python2
# -*- coding: utf-8 -*-
# 
# Copyright 2014 Marcus Müller.
# 
# This is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
# 
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this software; see the file COPYING.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street,
# Boston, MA 02110-1301, USA.
#

from mtb import TaskFrontend
import argparse

import sys
from PyQt4 import QtGui


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("JSON_FILE", type=argparse.FileType(mode='r'), nargs='?')
    parser.add_argument("-g", "--grc-file", action='store_true')
    args = parser.parse_args()
    app = QtGui.QApplication(sys.argv)
    ui = TaskFrontend()
    if not args.JSON_FILE is None:
        if not args.grc_file:
            ui._load_json_file_direct(args.JSON_FILE.name)
        else:
            print "loading GRC file"
            ui._import_grc_direct(args.JSON_FILE.name)
    sys.exit(app.exec_())
